version: '1.0-SNAPSHOT'
meta:
  ports:
    - 8095
  volumes:
    - logs:/var/crowd-home/logs
required:
  license:
    type: 'string'
    from: 'filesystem'
  baseUrl:
    type: 'string'
    from: 'input'
  serverId:
    type: 'string'
    from: 'input'
  subdirectory:
    type: 'string'
    from: 'input'
  password:
    type: 'string'
  username:
    type: 'string'
  first_name:
    type: 'string'
  last_name:
    type: 'string'
  mail:
    type: 'string'
  polytech_api:
    type: 'boolean'
  polytech_api_password:
    type: 'string'
  images:
    - postgres
    - nginx
postgres:
  postgresUser:
    type: 'string'
    from: 'postgres'
    name: 'userName'
  postgresPassword:
    type: 'string'
    from: 'postgres'
    name: 'password'
nginx:
  
