version: '1.0-SNAPSHOT'
required:
  certificate:
    type: 'binary'
    from: 'filesystem'
  key:
    type: 'binary'
    from: 'filesystem'

bitbucket:
    subdirectory:
    type: 'string'
    from: 'input'
crowd:
    subdirectory:
    type: 'string'
    from: 'input'
jira:
    subdirectory:
    type: 'string'
meta:
    ports:
        - 443
        - 80


  
