version: '1.0-SNAPSHOT'
required:


bitbucket:
    subdirectory:
    type: 'string'
    from: 'input'
crowd:
    subdirectory:
    type: 'string'
    from: 'input'
jira:
    subdirectory:
    type: 'string'
meta:
    port: 80


  
