version: '1.0-SNAPSHOT'
required:
  ssl:
    type: 'boolean'
  certificate:
    type: 'binary'
    from: 'filesystem'
    necessary: false
  key:
    type: 'binary'
    from: 'filesystem'
    necessary: false

bitbucket:
    subdirectory:
    type: 'string'
    from: 'input'
crowd:
    subdirectory:
    type: 'string'
    from: 'input'
jira:
    subdirectory:
    type: 'string'
meta:
    ports:
        - 443
        - 80


  
