version: '1.0-SNAPSHOT'
meta:
  ports:
    - 8080
  volumes:
    - data:/var/atlassian/application-data/jira/shared
    - logs:/var/atlassian/application-data/jira/log
required:
  license:
    type: 'string'
    from: 'filesystem'
  baseUrl:
    type: 'string'
    from: 'input'
  subdirectory:
    type: 'string'
    from: 'input'
  serverId:
    type: 'string'
  first_name:
    type: 'string'
  last_name:
    type: 'string'
  password:
    type: 'string'
  username:
    type: 'string'
  mail:
    type: 'string'
  keystore:
    type: 'binary'
    from: 'filesystem'
    necessary: False
  max_memory:
    type: 'string'
  self_signed:
    type: 'boolean'
  images:
    - postgres
    - nginx
postgres:

crowd:

bitbucket:

nginx:
