version: '1.0-SNAPSHOT'
meta:
  ports:
    - 8080
  volumes:
    - data:/var/atlassian/application-data/jira/shared/
required:
  license:
    type: 'string'
    from: 'filesystem'
  baseUrl:
    type: 'string'
    from: 'input'
  subdirectory:
    type: 'string'
    from: 'input'
  serverId:
    type: 'string'
  first_name:
    type: 'string'
  last_name:
    type: 'string'
  password:
    type: 'string'
  images:
    - postgres
    - nginx
postgres:
  postgresUser:
    type: 'string'
    from: 'postgres'
    name: 'userName'
  postgresPassword:
    type: 'string'
    from: 'postgres'
    name: 'password'
crowd:
  subdirectory:
    type: 'string'
  baseUrl:
    type: 'string'
bitbucket:
  subdirectory:
    type: 'string'
  baseUrl:
    type: 'string'
