version: '1.0-SNAPSHOT'
meta:
  ports:
    - 7990
  volumes:
    -  data:/var/atlassian/application-data/bitbucket/shared/data
    -  logs:/var/atlassian/application-data/bitbucket/log
required:
  license:
    type: 'string'
    from: 'filesystem'
  baseUrl:
    type: 'string'
    from: 'input'
  subdirectory:
    type: 'string'
    from: 'input'
  username:
    type: 'string'
  password:
    type: 'string'
  first_name:
    type: 'string'
  last_name:
    type: 'string'
  mail:
    type: 'string'
  serverId:
    type: 'string'
  keystore:
    type: 'binary'
    from: 'filesystem'
    necessary: False
  self_signed:
    type: 'boolean'
  max_memory:
    type: 'integer'
  images:
    - postgres
    - nginx
postgres:

nginx:
  

  
