version: '1.0-SNAPSHOT'
meta:
  ports:
    - 7990
  volumes:
    -  data:/var/atlassian/application-data/bitbucket/shared/data
    -  logs:/var/atlassian/application-data/bitbucket/log
required:
  files:
      - bitbucket.properties:/var/atlassian/application-data/bitbucket/shared/data
  license:
    type: 'string'
    from: 'filesystem'
  baseUrl:
    type: 'string'
    from: 'input'
  ownerName:
    type: 'string'
    from: 'input'
  ownerMail:
    type: 'string'
    from: 'input'
  subdirectory:
    type: 'string'
    from: 'input'
  username:
    type: 'string'
  password:
    type: 'string'
  first_name:
    type: 'string'
  last_name:
    type: 'string'
  mail:
    type: 'string'
  serverId:
    type: 'string'
  keystore:
    type: 'binary'
    from: 'filesystem'
  images:
    - postgres
    - nginx
postgres:
  postgresUser:
    type: 'string'
    from: 'postgres'
    name: 'userName'
  postgresPassword:
    type: 'string'
    from: 'postgres'
    name: 'password'
nginx:
  

  
