version: '1.0-SNAPSHOT'
meta:
  ports:
      - 5432
  volumes:
      - data:/var/lib/postgresql/data
required:
  postgresUser:
    type: 'string'
    from: 'postgres'
    name: 'userName'
  postgresPassword:
    type: 'string'
    from: 'postgres'
    name: 'password'

bitbucket:
  

  
crowd:
  

jira:
  

nginx:
  
